### ISSUE TITLE
SRD | 21A559 | macOS12.0.1 | X86_64 | 19C5026i | CryptexManager | unsuitable CT policy 0 for this platform/device, rejecting signature

### ISSUE THREAD

**Issue by xsscx** [pinauten/CryptexManager#1]
SRD | 21A559 | macOS12.0.1 | X86_64 | 19C5026i | CryptexManager | unsuitable CT policy 0 for this platform/device, rejecting signature

Hello!

I'm using an X86_64 with macOS 12.0.1 and iPhone11,8,iPhone12,1_15.2_19C5026i_Restore.ipsw on the SRD.

I got everything working up to the point of the cryptex not launching when using CryptexManager from X86_64 on macOs 12.0.1. Without flooding this Issue with Console Output, can you confirm that cryptex personalization is working with this current Release of Cryptex Manager when using macOS 12.0.1 from X86_64?

Of course, the issue could be operator error, let me know your thoughts.

Thanks!

I'm using this DMG: https://github.com/xsscx/srd/blob/main/dmg/19C5026i-toyboxunstripped.dmg

------------
X86_64 Host
```
.build/release/CryptexManager list                                                                                                                        
com.example.cryptex:
	Version: 1.3.3.7
	Mounted at: /private/var/run/com.apple.security.cryptexd/mnt/com.example.cryptex.0AAhj2
	Disk image path: /private/var/run/com.apple.security.cryptexd/codex.system/live/com.example.cryptex/cpxd
```
SRD Console
```
...
unsuitable CT policy 0 for this platform/device, rejecting signature
...
```

**Comment by LinusHenze** [comment]
Mhm, I cannot reproduce this issue but I'm on a different iOS version. The following worked for me:
1. Make sure no cryptex is installed (use `CryptexManager uninstall <id>` to uninstall)
2. Mount `19C5026i-toyboxunstripped.dmg`
3. Create cryptex: `CryptexManager  create -i com.example.cryptex -v 1.3.3.7 19C5026i-toyboxunstripped.dmg /Volumes/com.example.cryptex.dstroot /tmp/cptx`
4. Install cryptex: `CryptexManager  install /tmp/cptx`

**Comment by xsscx** [comment]
#Winner
